/* config.h generated by CMake from cmake/config.h.cmake.
 * Mirrors the defines configure.ac writes into the Autotools config.h. */

#ifndef FREEWRL_CMAKE_CONFIG_H
#define FREEWRL_CMAKE_CONFIG_H

/* Package */
#define PACKAGE "@PACKAGE@"
#define PACKAGE_NAME "@PACKAGE@"
#define PACKAGE_TARNAME "@PACKAGE@"
#define PACKAGE_VERSION "@PROJECT_VERSION@"
#define PACKAGE_STRING "@PACKAGE@ @PROJECT_VERSION@"
#define PACKAGE_BUGREPORT "@PACKAGE_BUGREPORT@"
#define PACKAGE_URL ""
#define VERSION "@PROJECT_VERSION@"

/* Headers */
#define STDC_HEADERS 1
#cmakedefine HAVE_CTYPE_H 1
#cmakedefine HAVE_DIRENT_H 1
#cmakedefine HAVE_DLFCN_H 1
#cmakedefine HAVE_ERRNO_H 1
#cmakedefine HAVE_FCNTL_H 1
#cmakedefine HAVE_GETOPT_H 1
#cmakedefine HAVE_INTTYPES_H 1
#cmakedefine HAVE_LIMITS_H 1
#cmakedefine HAVE_MATH_H 1
#cmakedefine HAVE_SCHED_H 1
#cmakedefine HAVE_SIGNAL_H 1
#cmakedefine HAVE_STDARG_H 1
#cmakedefine HAVE_STDBOOL_H 1
#cmakedefine HAVE_STDINT_H 1
#cmakedefine HAVE_STDIO_H 1
#cmakedefine HAVE_STDLIB_H 1
#cmakedefine HAVE_STRINGS_H 1
#cmakedefine HAVE_STRING_H 1
#cmakedefine HAVE_SYS_IOCTL_H 1
#cmakedefine HAVE_SYS_IPC_H 1
#cmakedefine HAVE_SYS_MSG_H 1
#cmakedefine HAVE_SYS_SOCKET_H 1
#cmakedefine HAVE_SYS_STAT_H 1
#cmakedefine HAVE_SYS_TIME_H 1
#cmakedefine HAVE_SYS_TYPES_H 1
#cmakedefine HAVE_SYS_WAIT_H 1
#cmakedefine HAVE_TIME_H 1
#cmakedefine HAVE_UNISTD_H 1
#cmakedefine HAVE_ZLIB_H 1
#cmakedefine HAVE__BOOL 1
#cmakedefine HAVE_X11_EXTENSIONS_XF86VMODE_H 1

/* Functions */
#cmakedefine HAVE_CALLOC 1
#cmakedefine HAVE_FORK 1
#cmakedefine HAVE_WORKING_FORK 1
#cmakedefine HAVE_VFORK 1
#cmakedefine HAVE_WORKING_VFORK 1
#cmakedefine HAVE_GETOPT 1
#cmakedefine HAVE_GETOPT_LONG 1
#cmakedefine HAVE_GETOPT_LONG_ONLY 1
#cmakedefine HAVE_GETTIMEOFDAY 1
#cmakedefine HAVE_MALLOC 1
#cmakedefine HAVE_REALLOC 1
#cmakedefine HAVE_STRCHR 1
#cmakedefine HAVE_STRDUP 1
#cmakedefine HAVE_STRERROR 1
#cmakedefine HAVE_STRNDUP 1
#cmakedefine HAVE_STRRCHR 1
#cmakedefine HAVE_USLEEP 1
#define RETSIGTYPE void

/* Libraries */
#define HAVE_LIBZ 1
#cmakedefine HAVE_PTHREAD 1
#cmakedefine HAVE_PTHREAD_CANCEL 1
#cmakedefine HAVE_FONTCONFIG 1
#cmakedefine HAVE_LIBCURL 1
#cmakedefine HAVE_IMLIB2 1
#cmakedefine HAVE_ALUT 1
#cmakedefine HAVE_OPENAL 1
#cmakedefine HAVE_OPENCL 1
#cmakedefine HAVE_XF86_VMODE 1
#cmakedefine MOVIETEXTURE_FFMPEG 1

/* Features */
#cmakedefine FW_DEBUG 1
#cmakedefine FREEWRL_THREAD_COLORIZED 1
#cmakedefine JAVASCRIPT_DUK 1
#cmakedefine JAVASCRIPT_STUB 1
#cmakedefine WITH_DIS 1
#cmakedefine WITH_RBP 1
#cmakedefine WANT_OSC 1
#cmakedefine WANT_2D_OVER 1
#cmakedefine INCLUDE_STL_FILES 1
#define STATUSBAR_HUD 1
#define USE_SNAPSHOT_TESTING 1

/* Paths and helper programs */
#define FONTS_DIR "@FREEWRL_FONTS_DIR@"
#define PLUGIN_DIR "@FREEWRL_PLUGIN_DIR@"
#define BROWSER "@FREEWRL_BROWSER@"
#define UNZIP "@FREEWRL_UNZIP@"
#cmakedefine WGET "@WGET@"
#define IMAGECONVERT "@FREEWRL_IMAGECONVERT@"

/* Program names */
#define FREEWRL_PROGRAM "freewrl"
#define FREEWRL_MESSAGE_WRAPPER "freewrl_msg"
#define FREEWRL_PLUGIN "libFreeWRLplugin.so"

#endif /* FREEWRL_CMAKE_CONFIG_H */
