/* config.h generated by CMake from cmake/config-macos.h.cmake.
 * Mirrors OSX_gui/FreeWRL-Desktop/FreeWRL/config.h, the config.h of the
 * Xcode FreeWRL target. Keep the two in step while the Xcode project exists. */

#ifndef FREEWRL_CMAKE_CONFIG_H
#define FREEWRL_CMAKE_CONFIG_H

#define FWVER "@FWVER@"

#cmakedefine FW_DEBUG 1

/* Aqua front end */
#define AQUA 1
#define TARGET_AQUA 1
#define XP_UNIX 1
#define FREEWRL_STEREO_RENDERING 1
#define FRONTEND_DOES_SNAPSHOTS 1
#define FRONTEND_HANDLES_DISPLAY_THREAD 1
#define STATUSBAR_HUD 1
#define STATUSBAR_STD 1
#define DO_COLLISION_GPU 1
/* Apple deprecated OpenGL in 10.14 but still ships 4.1 core; FreeWRL uses it knowingly */
#define GL_SILENCE_DEPRECATION 1
/* NURBS tessellation comes from GLU in OpenGL.framework */
#define HAVE_GLU_TESS 1
#define NURBS_LIB 1

/* Headers and functions */
#define STDC_HEADERS 1
#cmakedefine HAVE_CTYPE_H 1
#cmakedefine HAVE_DIRENT_H 1
#cmakedefine HAVE_ERRNO_H 1
#cmakedefine HAVE_FCNTL_H 1
#cmakedefine HAVE_GETOPT_H 1
#cmakedefine HAVE_INTTYPES_H 1
#cmakedefine HAVE_LIMITS_H 1
#cmakedefine HAVE_MATH_H 1
#cmakedefine HAVE_SCHED_H 1
#cmakedefine HAVE_STDARG_H 1
#cmakedefine HAVE_STDBOOL_H 1
#cmakedefine HAVE_STDINT_H 1
#cmakedefine HAVE_STDLIB_H 1
#cmakedefine HAVE_STRING_H 1
#cmakedefine HAVE_SYS_SOCKET_H 1
#cmakedefine HAVE_SYS_STAT_H 1
#cmakedefine HAVE_SYS_TIME_H 1
#cmakedefine HAVE_SYS_TYPES_H 1
#cmakedefine HAVE_SYS_WAIT_H 1
#cmakedefine HAVE_TIME_H 1
#cmakedefine HAVE_UNISTD_H 1
#cmakedefine HAVE_GETOPT_LONG 1
#cmakedefine HAVE_GETTIMEOFDAY 1
#cmakedefine HAVE_MEMCPY 1
#cmakedefine HAVE_STRNDUP 1
#cmakedefine HAVE_STRNLEN 1
#cmakedefine HAVE_PTHREAD 1

/* Libraries and features */
#cmakedefine HAVE_LIBCURL 1
#cmakedefine JAVASCRIPT_DUK 1
#cmakedefine JAVASCRIPT_STUB 1
#define JAVASCRIPT_ENGINE_VARIANT 1
#cmakedefine HAVE_ALUT 1
#cmakedefine HAVE_OPENAL 1
#cmakedefine WITH_RBP 1
#cmakedefine WITH_DIS 1
#cmakedefine MOVIETEXTURE_FFMPEG 1

/* Paths and helper programs */
#define FONTS_DIR "@FREEWRL_FONTS_DIR@"
#define FREEWRL_MESSAGE_WRAPPER "@FREEWRL_MESSAGE_WRAPPER@"
#define BROWSER "@FREEWRL_BROWSER@"
#define PACKAGE_BUGREPORT "@PACKAGE_BUGREPORT@"

#endif /* FREEWRL_CMAKE_CONFIG_H */
