#!/usr/bin/env python3
"""Generate the vrml.Invalid*Exception Java classes.

Run from this directory. Writes Invalid<Name>Exception.java here.

The output must stay byte-identical to the committed files, so the file
header still names genexceptions.pl.
"""

import sys

if sys.version_info < (3, 12):
    sys.exit("genexceptions.py: Python 3.12 or later is required.")

EXCEPTION_NAMES = (
    "EventIn",
    "EventOut",
    "ExposedField",
    "FieldChange",
    "Field",
    "Route",
)


def exception_source(exc):
    return (
        "//AUTOMATICALLY GENERATED BY genexceptions.pl.\n"
        "//DO NOT EDIT!!!!\n\n"
        f"package vrml;\n\npublic class {exc} extends IllegalArgumentException {{\n"
        f"    public {exc}() {{ super(); }}\n"
        f"    public {exc}(String s) {{ super(s); }}\n"
        "}\n"
    )


def main():
    for name in EXCEPTION_NAMES:
        exc = f"Invalid{name}Exception"
        with open(f"{exc}.java", "w", encoding="ascii", newline="\n") as out:
            out.write(exception_source(exc))


if __name__ == "__main__":
    main()
