#!/usr/bin/env python3
"""Generate the FreeWRL node tables from vrml_nodes.py.

This is the Python form of VRMLC.pm. It writes these files below freex3d/:

    src/lib/scenegraph/GeneratedCode.c
    src/libeai/GeneratedCode.c
    src/lib/vrml_parser/NodeFields.h
    src/lib/vrml_parser/Structs.h

The output must stay byte-identical to the VRMLC.pm output. The generated
text still names VRMLC.pm and Perl. Change that text only in a separate
change that also updates the generated files.

Usage:
    python3 vrmlc.py               write the files in this source tree
    python3 vrmlc.py --check       compare with the files, write nothing
    python3 vrmlc.py --out-dir D   write the files below D instead

The script builds all four files in memory first. It writes a file only
when its content changes, and it replaces the files only after all new
files are ready.
"""

import sys

if sys.version_info < (3, 12):
    sys.exit("vrmlc.py: Python 3.12 or later is required.")

sys.dont_write_bytecode = True

import argparse  # noqa: E402
import os  # noqa: E402
import tempfile  # noqa: E402
from pathlib import Path  # noqa: E402

CODEGEN_DIR = Path(__file__).resolve().parent
FREEX3D_DIR = CODEGEN_DIR.parent
sys.path.insert(0, str(CODEGEN_DIR))

from vrml_fields import C_STRUCT, FIELD_TYPES, FieldDataError, cinitialize, ctype  # noqa: E402

try:
    # vrml_nodes checks the node data when it loads.
    import vrml_rend  # noqa: E402
    from vrml_nodes import NODES  # noqa: E402
except ValueError as err:
    sys.exit(f"vrmlc.py: error: bad generator data: {err}")

LICENSE_FILE = FREEX3D_DIR / "versions" / "template" / "license.c.in"

SCENEGRAPH_C = "src/lib/scenegraph/GeneratedCode.c"
LIBEAI_C = "src/libeai/GeneratedCode.c"
NODEFIELDS_H = "src/lib/vrml_parser/NodeFields.h"
STRUCTS_H = "src/lib/vrml_parser/Structs.h"

# Write order of VRMLC.pm.
OUTPUTS = (SCENEGRAPH_C, LIBEAI_C, NODEFIELDS_H, STRUCTS_H)


class GenerateError(Exception):
    """A problem that stops generation before any file is written."""


# The fields at the start of every node struct, and of struct X3D_Node.
COMMON_FIELDS = (
    "       int _nodeType; /* unique integer for each type */ \n"
    "       int _renderFlags; /*sensitive, etc */ \n"
    "       int _hit; \n"
    "       int _change; \n"
    "       int _ichange; \n"
    "       char * _fieldchange; \n"
    "       struct Vector* _parentVector; \n"
    "       double _dist; /*sorting for blending */ \n"
    "       float _extent[6]; /* used for boundingboxes - +-x, +-y, +-z */ \n"
    "       struct X3D_GeomRep *_intern; \n"
    "       int referenceCount; /* if this reaches zero, nobody wants it anymore */ \n"
    "       int _defaultContainer; /* holds the container */\n"
    "       void* _gc; /* ptr to vector of ptrs to free */\n"
    "       struct X3D_Node* _executionContext; /* scene or protoInstance */\n"
    " \t/*** node specific data: *****/\n"
)

# C function name prefix of each virtual-table slot.
SLOT_PREFIX = {
    "Prep": "prep",
    "Rend": "render",
    "Child": "child",
    "Fin": "fin",
    "RendRay": "rendray",
    "GenPolyRep": "make",
    "Proximity": "proximity",
    "Other": "other",
    "Collision": "collide",
    "Compile": "compile",
}

# These nodes share common collide_, make_ and rendray_ functions, so they
# get no prototype of their own.
SHARED_COLLIDE_MAKE = frozenset((
    "ElevationGrid",
    "IndexedFaceSet",
    "IndexedTriangleFanSet",
    "IndexedTriangleSet",
    "IndexedTriangleStripSet",
    "TriangleFanSet",
    "TriangleSet",
    "TriangleStripSet",
    "QuadSet",
    "IndexedQuadSet",
    "GeoElevationGrid",
))
SHARED_RENDRAY = SHARED_COLLIDE_MAKE | {"Extrusion", "Text"}

NO_PROTOTYPE = {
    "Collision": SHARED_COLLIDE_MAKE,
    "GenPolyRep": SHARED_COLLIDE_MAKE,
    "RendRay": SHARED_RENDRAY,
}

SCENEGRAPH_INCLUDES = (
    "/*\n"
    "  GeneratedCode.c: generated by VRMLC.pm. DO NOT MODIFY, MODIFY VRMLC.pm INSTEAD.\n"
    "*/\n"
    " \n"
    "#include <config.h> \n"
    "#include <system.h> \n"
    "#include <display.h> \n"
    "#include <internal.h> \n"
    " \n"
    "#include <libFreeWRL.h> \n"
    "#include <io_files.h> \n"
    " \n"
    "#include \"../vrml_parser/Structs.h\" \n"
    "#include \"../main/headers.h\" \n"
    "#include \"../main/ProdCon.h\" \n"
    "#include \"Component_Networking.h\" \n"
    "#include \"Component_Picking.h\" \n"
    "#include \"../list.h\" \n"
    "#include \"../io_http.h\" \n"
    " \n"
    " \n"
    "/**********************************************************************************************/ \n"
    "/*                                                                                            */ \n"
    "/* This file is part of the FreeWRL/FreeX3D Distribution, from http://freewrl.sourceforge.net */ \n"
    "/*                                                                                            */ \n"
    "/**********************************************************************************************/ \n"
    " \n"
    "#include \"../input/EAIHeaders.h\" \n"
    "#include \"../input/EAIHelpers.h\" \n"
    "#include \"../x3d_parser/Bindable.h\" \n"
    " \n"
    "#include \"../opengl/Textures.h\" \n"
    "#include \"Component_CubeMapTexturing.h\" \n"
    "#include \"Polyrep.h\" \n"
    "void add_OSCsensor(struct X3D_Node* node); /* WANT_OSC*/\n"
    "void addNodeToKeySensorList(struct X3D_Node* node);\n"
    "void collide_genericfaceset (struct X3D_IndexedFaceSet *node );\n"
    "void make_genericfaceset(struct X3D_IndexedFaceSet *this_);\n"
    "void render_ray_polyrep(void *node);\n"
    "void dump_scene(FILE *fp, int level, struct X3D_Node* node);\n"
    "extern char *parser_getNameFromNode(struct X3D_Node* node);\n"
)

SCAN_MACROS = (
    "/* definitions to help scanning values in from a string */ \n"
    "#define SCANTONUMBER(value) while (isspace(*value) || (*value==',')) value++; \n"
    "#define SCANTOSTRING(value) while (isspace(*value) || (*value==',')) value++; \n"
    "#define OLDSCANTOSTRING(value) while ((*value==' ') || (*value==',')) value++; \n"
    "#define ISSTARTNUMBER(value) (isdigit(*value) \\\n"
    "\t\t|| (*value == '+') || (*value == '-')) \n"
    "#define SCANPASTFLOATNUMBER(value) while (isdigit(*value) \\\n"
    "\t\t|| (*value == '.') || \\\n"
    "\t\t(*value == 'E') || (*value == 'e') || (*value == '+') || (*value == '-')) value++; \n"
    "#define SCANPASTINTNUMBER(value) if (isdigit(*value) || (*value == '-') || (*value == '+')) value++; \\\n"
    "\t\twhile (isdigit(*value) || \\\n"
    "\t\t(*value == 'x') || (*value == 'X') ||\\\n"
    "\t\t((*value >='a') && (*value <='f')) || \\\n"
    "\t\t((*value >='A') && (*value <='F')) || \\\n"
    "\t\t(*value == '-') || (*value == '+')) value++; \n"
)

EAI_INCLUDES = (
    "#include <config.h>\n"
    "#include <system.h>\n"
    "#include <display.h>\n"
    "\n"
    "#include <vrml_parser/Structs.h>\n"
    "#include <main/headers.h>\n"
    "#include <input/EAIHeaders.h>\n"
    "\n"
)

NODE_MACROS = (
    "#define X3D_POINTPROPERTIES(node) ((struct X3D_PointProperties*)node)\n"
    "#define X3D_LINEPROPERTIES(node) ((struct X3D_LineProperties*)node)\n"
    "#define X3D_FILLPROPERTIES(node) ((struct X3D_FillProperties*)node)\n"
    "#define X3D_TEXTURE_TRANSFORM(node) ((struct X3D_TextureTransform*)node)\n"
    "#define X3D_NODE(node) ((struct X3D_Node*)node)\n"
    "#define X3D_APPEARANCE(node) ((struct X3D_Appearance*)node)\n"
    "#define X3D_MATERIAL(node) ((struct X3D_Material*)node)\n"
    "#define X3D_TWOSIDEDMATERIAL(node) ((struct X3D_TwoSidedMaterial*)node)\n"
    "#define X3D_GROUP(node) ((struct X3D_Group*)node)\n"
    "#define X3D_PROTO(node) ((struct X3D_Proto*)node)\n"
    "#define X3D_PICKABLEGROUP(node) ((struct X3D_PickableGroup*)node)\n"
    "#define X3D_POINTPICKSENSOR(node) ((struct X3D_PointPickSensor*)node)\n"
    "#define X3D_STATICGROUP(node) ((struct X3D_StaticGroup*)node)\n"
    "#define X3D_ANCHOR(node) ((struct X3D_Anchor*)node)\n"
    "#define X3D_COLLISION(node) ((struct X3D_Collision*)node)\n"
    "#define X3D_COMPOSEDSHADER(node) ((struct X3D_ComposedShader*)node)\n"
    "#define X3D_EFFECT(node) ((struct X3D_Effect*)node)\n"
    "#define X3D_PACKAGEDSHADER(node) ((struct X3D_PackagedShader*)node)\n"
    "#define X3D_PROGRAMSHADER(node) ((struct X3D_ProgramShader*)node)\n"
    "#define X3D_SHADERPROGRAM(node) ((struct X3D_ShaderProgram*)node)\n"
    "#define X3D_SHAPE(node) ((struct X3D_Shape*)node)\n"
    "#define X3D_VISIBILITYSENSOR(node) ((struct X3D_VisibilitySensor*)node)\n"
    "#define X3D_BILLBOARD(node) ((struct X3D_Billboard*)node)\n"
    "#define X3D_NAVIGATIONINFO(node) ((struct X3D_NavigationInfo*)node)\n"
    "#define X3D_BACKGROUND(node) ((struct X3D_Background*)node)\n"
    "#define X3D_TEXTUREBACKGROUND(node) ((struct X3D_TextureBackground*)node)\n"
    "#define X3D_FOG(node) ((struct X3D_Fog*)node)\n"
    "#define X3D_INLINE(node) ((struct X3D_Inline*)node)\n"
    "#define X3D_SWITCH(node) ((struct X3D_Switch*)node)\n"
    "#define X3D_CADASSEMBLY(node) ((struct X3D_CADAssembly*)node)\n"
    "#define X3D_CADFACE(node) ((struct X3D_CADFace*)node)\n"
    "#define X3D_CADLAYER(node) ((struct X3D_CADLayer*)node)\n"
    "#define X3D_CADPART(node) ((struct X3D_CADPart*)node)\n"
    "#define X3D_SCRIPT(node) ((struct X3D_Script*)node)\n"
    "#define X3D_VIEWPOINT(node) ((struct X3D_Viewpoint*)node)\n"
    "#define X3D_ORTHOVIEWPOINT(node) ((struct X3D_OrthoViewpoint*)node)\n"
    "#define X3D_LODNODE(node) ((struct X3D_LOD*)node)\n"
    "#define X3D_TRANSFORM(node) ((struct X3D_Transform*)node)\n"
    "#define X3D_PROXIMITYSENSOR(node) ((struct X3D_ProximitySensor*)node)\n"
    "#define X3D_POINTLIGHT(node) ((struct X3D_PointLight*)node)\n"
    "#define X3D_SPOTLIGHT(node) ((struct X3D_SpotLight*)node)\n"
    "#define X3D_DIRECTIONALLIGHT(node) ((struct X3D_DirectionalLight*)node)\n"
    "#define X3D_ENVIRONMENTLIGHT(node) ((struct X3D_EnvironmentLight*)node)\n"
    "#define X3D_INDEXEDFACESET(node) ((struct X3D_IndexedFaceSet*)node)\n"
    "#define X3D_INDEXEDLINESET(node) ((struct X3D_IndexedLineSet*)node)\n"
    "#define X3D_ELEVATIONGRID(node) ((struct X3D_ElevationGrid*)node)\n"
    "#define X3D_INDEXEDTRIANGLEFANSET(node) ((struct X3D_IndexedTriangleFanSet*)node)\n"
    "#define X3D_INDEXEDTRIANGLESET(node) ((struct X3D_IndexedTriangleSet*)node)\n"
    "#define X3D_INDEXEDTRIANGLESTRIPSET(node) ((struct X3D_IndexedTriangleStripSet*)node)\n"
    "#define X3D_TRIANGLEFANSET(node) ((struct X3D_TriangleFanSet*)node)\n"
    "#define X3D_TRIANGLESET(node) ((struct X3D_TriangleSet*)node)\n"
    "#define X3D_TRIANGLESTRIPSET(node) ((struct X3D_TriangleStripSet*)node)\n"
    "#define X3D_QUADSET(node) ((struct X3D_QuadSet*)node)\n"
    "#define X3D_INDEXEDQUADSET(node) ((struct X3D_IndexedQuadSet*)node)\n"
    "#define X3D_ORTHOTEXTURE(node) ((struct X3D_OrthoTexture*)node)\n"
    "#define X3D_VIEWPORT(node) ((struct X3D_Viewport*)node)\n"
    "#define X3D_LAYOUT(node) ((struct X3D_Layout*)node)\n"
    "#define X3D_LAYERSET(node) ((struct X3D_LayerSet*)node)\n"
    "#define X3D_AUDIO(node) ((struct X3D_AudioNode*)node)\n"
    "#define X3D_GEOORIGIN(node) ((struct X3D_GeoOrigin*)node)\n"
    "#define X3D_GEOLOD(node) ((struct X3D_GeoLOD*)node)\n"
    "#define X3D_GEOCOORD(node) ((struct X3D_GeoCoordinate*)node)\n"
    "#define X3D_GEOVIEWPOINT(node) ((struct X3D_GeoViewpoint*)node)\n"
    "#define X3D_GEOELEVATIONGRID(node) ((struct X3D_GeoElevationGrid*)node)\n"
    "#define X3D_GEOLOCATION(node) ((struct X3D_GeoLocation*)node)\n"
    "#define X3D_GEOTRANSFORM(node) ((struct X3D_GeoTransform*)node)\n"
    "#define X3D_GEOPROXIMITYSENSOR(node) ((struct X3D_GeoProximitySensor*)node)\n"
    "#define X3D_COLOR(node) ((struct X3D_Color*)node)\n"
    "#define X3D_COORDINATE(node) ((struct X3D_Coordinate*)node)\n"
    "#define X3D_COORDINATEINTERPOLATOR(node) ((struct X3D_CoordinateInterpolator*)node)\n"
    "#define X3D_NORMAL(node) ((struct X3D_Normal*)node)\n"
    "#define X3D_TEXTURECOORDINATE(node) ((struct X3D_TextureCoordinate*)node)\n"
    "#define X3D_IMAGETEXTURE(node) ((struct X3D_ImageTexture*)node)\n"
    "#define X3D_TEXTUREPROPERTIES(node) ((struct X3D_TextureProperties*)node)\n"
    "#define X3D_PIXELTEXTURE(node) ((struct X3D_PixelTexture*)node)\n"
    "#define X3D_BUFFERTEXTURE(node) ((struct X3D_BufferTexture*)node)\n"
    "#define X3D_TEXTUREPROJECTOR(node) ((struct X3D_TextureProjector*)node)\n"
    "#define X3D_TEXTUREPROJECTORPARALLEL(node) ((struct X3D_TextureProjectorParallel*)node)\n"
    "#define X3D_TEXTUREPROJECTORPOINT(node) ((struct X3D_TextureProjectorPoint*)node)\n"
    "void mark_event (struct X3D_Node *from, int totalptr);\n"
    "#undef DEBUG_VALIDNODE\n"
    "#ifdef DEBUG_VALIDNODE\t\n"
    "#define X3D_NODE_CHECK(node) checkNode(node,__FILE__,__LINE__)\n"
    "#define MARK_EVENT(node,offset) mark_event_check(node,(int) offset,__FILE__,__LINE__)\n"
    "#else\n"
    "#define X3D_NODE_CHECK(node)\n"
    "#define MARK_EVENT(node,offset)\tmark_event(node,(int) offset)\n"
    "#endif\n"
    "#define COPY_SFVEC3F_TO_POINT_XYZ(too,from) { too.x = from[0]; too.y = from[1]; too.z = from[2];}\n"
    "#define COPY_POINT_XYZ_TO_SFVEC3F(too,from) { too[0] = (float) from.x; too[1] = (float) from.y; too[2] = (float) from.z;}\n"
    "#define offsetPointer_deref(t, me, offs) ((t)(((char*)(me))+offs))\n"
)

CREATE_NODE0_HEAD = (
    "/* create a new node of type. This can be generated by Perl code, much as the Structs.h is */\n"
    "void *createNewX3DNode0 (int nt) {\n"
    "\tvoid * tmp;\n"
    "\tint size;\n"
    "\tstruct X3D_Box *node;\n"
    "\n"
    "\ttmp = NULL;\n"
    "\tsize = 0;\n"
    "\tswitch (nt) {\n"
)

CREATE_NODE0_COMMON = (
    "\t}\n\n"
    "\t/* now, fill in the node to DEFAULT values This mimics \"alloc_struct\" in the Perl code. */\n"
    "\t/* the common stuff between all nodes. We'll use a X3D_Box struct, just because. It is used\n"
    "\t   in this way throughought the code */\n"
    "\tnode = (struct X3D_Box *) tmp;\n"
    "\tnode->_renderFlags = 0; /*sensitive, etc */\n"
    "\tnode->_hit = 0;\n"
    "\tnode->_change = NODE_CHANGE_INIT_VAL; \n"
    "\tnode->_fieldchange = malloc(size/32); \n"
    "\tnode->_parentVector = newVector(struct X3D_Node*, 1);\n"
    "\tnode->_ichange = 0;\n"
    "\tnode->_dist = -10000.0; /*sorting for blending */\n"
    "\tINITIALIZE_EXTENT\n"
    "\tnode->_intern = 0;\n"
    "\tnode->_nodeType = nt; /* unique integer for each type */\n"
    "\tnode->referenceCount = 1; /* we have requested this, we want it! */\n"
    "\tnode->_gc = NULL; /* any node doing non-public field mallocs can register_node_gc(node,p) for auto-freeing */ \n"
    "\tnode->_executionContext = NULL; /* a few places like js need to know the executionContext if non-null */ \n"
    "\t\n"
    "\t/* now, fill in the node specific stuff here. the defaults are in VRMLNodes.pm */\n"
    "\tswitch (nt) {\n"
)

CREATE_NODE = (
    "/* create a new node of type. This can be generated by Perl code, much as the Structs.h is */\n"
    "void *createNewX3DNode (int nt) {\n"
    "\tvoid * tmp;\n"
    "\ttmp = createNewX3DNode0(nt);\n"
    "\t\n"
    "\t/* is this a texture holding node? */\n"
    "\tregisterTexture(tmp);\n"
    "\t/* Node Tracking */\n"
    "\tregisterX3DNode(tmp);\n"
    "\t/* is this a bindable node? */\n"
    "\tregisterBindable(tmp);\n"
    "\t/* is this a OSC sensor node? */\n"
    "\tadd_OSCsensor(tmp); /* WANT_OSC */\n"
    "\t/* is this a pick sensor node? */\n"
    "\tadd_picksensor(tmp); /* DJTRACK_PICKSENSORS */\n"
    "\t/* is this a time tick node? */\n"
    "       add_first(tmp);\n"
    "       /* possibly a physics node? */\n"
    "       add_physics(X3D_NODE(tmp));\n"
    "       /* possibly a KeySensor node? */\n"
    "       addNodeToKeySensorList(X3D_NODE(tmp));\n"
    "\treturn tmp;\n}\n"
)

DUMP_SCENE_HEAD = (
    "/* Dump the scene graph.  */\n"
    "#define Boolean int\n"
    "void dump_scene (FILE *fp, int level, struct X3D_Node* node) {\n"
    "\t#define spacer\tfor (lc=0; lc<level; lc++) fprintf (fp,\" \");\n"
    "\tint lc;\n"
    "\tint i;\n"
    "\tchar *nodeName;\n"
    "\t#ifdef FW_DEBUG\n\t\tBoolean allFields;\n"
    "\t\tif (fileno(fp) == fileno(stdout)) { allFields = TRUE; } else { allFields = FALSE; }\n"
    "\t#else\n\t\tBoolean allFields = FALSE;\n\t#endif\n"
    "\t/* See vi +/double_conditional codegen/VRMLC.pm */\n"
    "\tif (node==NULL) return; \n\n"
    "\tfflush(fp);\n"
    "\tif (level == 0) fprintf (fp,\"starting dump_scene\\n\");\n"
    "\tnodeName = parser_getNameFromNode(node) ;\n"
    "\tif (nodeName == NULL) {\n"
    "\t\tspacer fprintf (fp,\"L%d: node (%p) () type %s\\n\",level,node,stringNodeType(node->_nodeType));\n"
    "\t} else {\n"
    "\t\tspacer fprintf (fp,\"L%d: node (%p) (DEF %s) type %s\\n\",level,node,nodeName,stringNodeType(node->_nodeType));\n"
    "\t}\n"
    "\tswitch (node->_nodeType) {\n"
)

DUMP_SCENE_TAIL = (
    "\t\tdefault: {}\n"
    " }\n fflush(fp) ;\n spacer fprintf (fp,\"L%d end\\n\",level);\n"
    " if (level == 0) fprintf (fp,\"ending dump_scene\\n\");\n}\n"
)

# Number of values that dump_scene prints for the fixed-size SF types.
DUMP_SF_LENGTH = {
    "SFRotation": 4, "SFColorRGBA": 4,
    "SFVec4f": 4, "SFVec4d": 4,
    "SFColor": 3, "SFVec3f": 3, "SFVec3d": 3,
    "SFVec2f": 2, "SFVec2d": 2,
    "SFMatrix3f": 9, "SFMatrix3d": 9,
    "SFMatrix4f": 16, "SFMatrix4d": 16,
}

# printf format of one MF element in dump_scene.
DUMP_MF_FORMAT = {
    "MFVec3f": "[%4.3f, %4.3f, %4.3f]",
    "MFColor": "[%4.3f, %4.3f, %4.3f]",
    "MFVec3d": "[%4.3f, %4.3f, %4.3f]",
    "MFVec2f": "[%4.3f, %4.3f]",
    "MFVec2d": "[%4.3f, %4.3f]",
    "MFRotation": "[%4.3f, %4.3f, %4.3f, %4.3f]",
    "MFColorRGBA": "[%4.3f, %4.3f, %4.3f, %4.3f]",
    "MFVec4f": "[%4.3f, %4.3f, %4.3f, %4.3f]",
    "MFVec4d": "[%4.3f, %4.3f, %4.3f, %4.3f]",
    "MFMatrix4f": "[%4.3f, %4.3f, %4.3f, %4.3f, %4.3f,  %4.3f,  %4.3f,  %4.3f,  %4.3f, "
                  "%4.3f, %4.3f, %4.3f, %4.3f, %4.3f,  %4.3f,  %4.3f ]",
    "MFMatrix4d": "[%4.3f, %4.3f, %4.3f, %4.3f, %4.3f,  %4.3f,  %4.3f,  %4.3f,  %4.3f, "
                  "%4.3f, %4.3f, %4.3f, %4.3f, %4.3f,  %4.3f,  %4.3f ]",
    "MFMatrix3f": "[%4.3f, %4.3f, %4.3f, %4.3f, %4.3f,  %4.3f,  %4.3f,  %4.3f,  %4.3f ]",
    "MFMatrix3d": "[%4.3f, %4.3f, %4.3f, %4.3f, %4.3f,  %4.3f,  %4.3f,  %4.3f,  %4.3f ]",
}

NODEFIELDS_INTRO = (
    "\n"
    "/*\n"
    "Information for all the fields of all the nodes.\n"
    "\n"
    "Format is as follows:\n"
    "BEGIN_NODE(NodeName)\n"
    " FIELD(Node, field, type, varToAssignInStruct)\n"
    " EXPOSED_FIELD(Node, field, type, varToAssignInStruct)\n"
    " EVENT_IN(Node, event, type, varToAssignInStruct)\n"
    " EVENT_OUT(Node, event, type, varToAssignInStruct)\n"
    "END_NODE(NodeName)\n"
    "\n"
    "*/\n"
    "\n"
)

STRUCTS_INTRO = (
    "\n"
    "#ifndef __FREEWRL_STRUCTS_H__\n"
    "#define __FREEWRL_STRUCTS_H__\n"
    "\n"
    "//#include <system_threads.h>\n"
    "struct point_XYZ {GLDOUBLE x,y,z;};\n"
    "union upoint_XYZ { struct point_XYZ p; GLDOUBLE c[3]; };\n"
    "// initialize like this: \tunion upoint_XYZ uxyz = { .c = {1,2,3} }; \n"
    "// or this: uxyz = {.p.x = 1, .p.y = 2, .p.z = 3 };\n"
    "struct orient_XYZA {GLDOUBLE x,y,z,a;};\n"
    "\n"
    "struct X3D_Virt {\n"
    "\tvoid (*prep)(void *);\n"
    "\tvoid (*rend)(void *);\n"
    "\tvoid (*children)(void *);\n"
    "\tvoid (*fin)(void *);\n"
    "\tvoid (*rendray)(void *);\n"
    "\tvoid (*mkpolyrep)(void *);\n"
    "\tvoid (*proximity)(void *);\n"
    "\tvoid (*other)(void *);\n"
    "\tvoid (*collision)(void *);\n"
    "\tvoid (*compile)(void *, void *, void *, void *, void *, void *);\n"
    "};\n"
    "\n"
    "/* a string is stored as a pointer, and a length of that mallocd pointer */\n"
    "struct Uni_String {\n"
    "\tint len;\n"
    "\tchar * strptr;\n"
    "\tint touched;\n"
    "};\n"
    "\n"
    "\n"
)

STRUCTS_END = "\n#endif /* __FREEWRL_STRUCTS_H__ */\n"

NODEFIELDS_KIND = {
    "outputOnly": "EVENT_OUT",
    "inputOnly": "EVENT_IN",
    "inputOutput": "EXPOSED_FIELD",
    "initializeOnly": "FIELD",
}


def file_header(name, extra=""):
    return (
        "/*\n"
        "\n"
        f"  {name}: generated by VRMLC.pm. DO NOT MODIFY, MODIFY VRMLC.pm INSTEAD.\n"
        "\n"
        f"{extra}"
        "*/\n"
    )


def gen_struct(name, node):
    out = f"/***********************/\nstruct X3D_{name} {{\n" + COMMON_FIELDS
    for field in node.fields:
        out += f"\t{ctype(field.type, field.name)};\n"
    return out + "};\n"


def get_rendfunc(name):
    """Return the extern line and the prototypes plus virt_<name> table."""
    present = [(slot, name in names) for slot, names in vrml_rend.RENDER_SLOTS]
    out = "\n"
    for slot, has in present:
        if has and name not in NO_PROTOTYPE.get(slot, ()):
            out += f"void {SLOT_PREFIX[slot]}_{name}(struct X3D_{name} *);\n"
    entries = [f"(void *){SLOT_PREFIX[slot]}_{name}" if has else "NULL" for slot, has in present]
    out += f"struct X3D_Virt virt_{name} = {{ " + ",".join(entries) + "};\n"
    return f"extern struct X3D_Virt virt_{name};\n", out


def string_function(g2, st, what, func, array, invalid):
    g2.append(
        f"/* Return a pointer to a string representation of the {what} type */\n"
        f"const char *{func} (int st) {{\n"
        f"\tif ((st < 0) || (st >= {array}_COUNT)) return \"({invalid} invalid)\"; \n"
        f"\treturn {array}[st];\n}}\n\n"
    )
    st.append(f"const char *{func}(int st);\n")


def name_table(st, g1, builtin, array, title, names, define, indent="       "):
    """Write one string table and its #defines. Return the #define lines."""
    st.append(f"\n/* Table of built-in {builtin} */\nextern const char *{array}[];\n")
    st.append(f"extern const int {array}_COUNT;\n")
    g1.append(f"\n/* Table of {title} */\n{indent}const char *{array}[] = {{\n")
    defines = []
    for number, name in enumerate(names):
        line = define(name, number)
        defines.append(line)
        st.append(line + "\n")
        g1.append(f"\t\"{name}\",\n")
    st.append("\n")
    g1.append(f"}};\nconst int {array}_COUNT = ARR_SIZE({array});\n\n")
    return defines


def defs_string(macro, defines):
    # A C string with one "#define ..\n" line for each entry.
    return f"#define {macro} \" \\\n" + "".join(d + "\\n \\\n" for d in defines) + "\";\n"


def dump_field(field):
    f, t = field.name, field.type
    if t == "FreeWRLPTR":
        return f"\t\t\tspacer fprintf (fp,\" {f} ({t}) (void pointer, not dumped)\\n\");\n"
    if t == "FreeWRLThread":
        return f"\t\t\tspacer fprintf (fp,\" {f} ({t}) (thread pointer, not dumped)\\n\");\n"
    if t in ("SFInt32", "SFBool"):
        return f"\t\t\tspacer fprintf (fp,\" {f} ({t}) \\t%d\\n\",tmp->{f});\n"
    if t in ("SFFloat", "SFTime", "SFDouble"):
        return f"\t\t\tspacer fprintf (fp,\" {f} ({t}) \\t%4.3f\\n\",tmp->{f});\n"
    if t == "SFString":
        return f"\t\t\tspacer fprintf (fp,\" {f} ({t}) \\t%s\\n\",tmp->{f}->strptr);\n"
    if t == "SFNode":
        return f"\t\t\tspacer fprintf (fp,\" {f} ({t}):\\n\"); dump_scene(fp,level+1,tmp->{f}); \n"
    if t in DUMP_SF_LENGTH:
        return (f"\t\t\tspacer fprintf (fp,\" {f} ({t}): \\t\");\n"
                f"\t\t\tfor (i=0; i<{DUMP_SF_LENGTH[t]}; i++) {{ fprintf (fp,\"%4.3f  \",tmp->{f}.c[i]); }}\n"
                "\t\t\tfprintf (fp,\"\\n\");\n")
    if t == "SFImage":
        return (f"\t\t\tspacer fprintf (fp,\" {f} ({t}): (not dumped)\\t\");\n"
                "\t\t\tfprintf (fp,\"\\n\");\n")
    if t == "MFString":
        return (f"\t\t\tspacer fprintf (fp,\" {f} ({t}): \\n\");\n"
                f"\t\t\tfor (i=0; i<tmp->{f}.n; i++) {{ spacer fprintf (fp,\"\t\t\t%d: \\t%s\\n\",i,tmp->{f}.p[i]->strptr); }}\n")
    if t == "MFNode":
        return (f"\t\t\tspacer fprintf (fp,\" {f} ({t}):\\n\");\n"
                f"\t\t\tfor (i=0; i<tmp->{f}.n; i++) {{ dump_scene(fp,level+1,tmp->{f}.p[i]); }}\n")
    if t in ("MFInt32", "MFBool", "MFFloat", "MFTime", "MFDouble"):
        fmt = "%d" if t in ("MFInt32", "MFBool") else "%4.3f"
        return (f"\t\t\tspacer fprintf (fp,\" {f} ({t}):\\n\");\n"
                f"\t\t\tfor (i=0; i<tmp->{f}.n; i++) {{ spacer fprintf (fp,\"\t\t\t%d: \\t{fmt}\\n\",i,tmp->{f}.p[i]); }}\n")
    if t in DUMP_MF_FORMAT:
        count = DUMP_MF_FORMAT[t].count("%")
        args = f"(tmp->{f}.p[i]).c[0], " + ",".join(f"(tmp->{f}.p[i]).c[{k}]" for k in range(1, count))
        return (f"\t\t\tspacer fprintf (fp,\" {f} ({t}):\\n\");\n"
                f"\t\t\tfor (i=0; i<tmp->{f}.n; i++) {{ spacer "
                f"fprintf (fp,\"\t\t\t%d: \\t{DUMP_MF_FORMAT[t]}\\n\",i,{args}); }}\n")
    # VRMLC.pm prints "type ... not handled yet", writes no dump code for
    # the field and continues. Keep it.
    print(f"type {t} not handled yet")
    return ""


def generate(license_text):
    """Return {output path: text} for the four generated files."""
    node_names = sorted(NODES)

    g1 = [SCENEGRAPH_INCLUDES]
    g2 = []
    st = [SCAN_MACROS, "/* Data type for index into ID-table. */\ntypedef int indexT;\n\n"]
    eai = [EAI_INCLUDES]

    # Node numbers, and the names of all fields by kind.
    all_fields = set()
    by_kind = {kind: set() for kind in NODEFIELDS_KIND}
    for number, name in enumerate(node_names):
        st.append(f"#define NODE_{name}\t{number}\n")
        for field in NODES[name].fields:
            all_fields.add(field.name)
            by_kind[field.kind].add(field.name)
    st.append("\n")

    name_table(st, g1, "fieldIds", "FIELDNAMES", "built-in fieldIds", sorted(all_fields),
               lambda n, i: f"#define FIELDNAMES_{n}\t{i}")
    string_function(g2, st, "field", "stringFieldType", "FIELDNAMES", "fieldName")

    # Field names that start with "_" are internal, so they are left out.
    for array, title, kind in (
        ("EVENT_OUT", "EVENT_OUTs", "outputOnly"),
        ("EVENT_IN", "EVENT_INs", "inputOnly"),
        ("EXPOSED_FIELD", "EXPOSED_FIELDs", "inputOutput"),
        ("FIELD", "FIELDs", "initializeOnly"),
    ):
        names = [n for n in sorted(by_kind[kind]) if not n.startswith("_")]
        name_table(st, g1, "fieldIds", array, title, names,
                   lambda n, i, a=array: f"#define {a}_{n}\t{i}")

    name_table(st, g1, "keywords", "KEYWORDS", "keywords", sorted(vrml_rend.KeywordC),
               lambda n, i: f"#define KW_{n}\t{i}")
    string_function(g2, st, "keyword", "stringKeywordType", "KEYWORDS", "keyword")

    # C names can not have "-".
    name_table(st, g1, "profiles", "PROFILES", "profiles", sorted(vrml_rend.ProfileC),
               lambda n, i: f"#define PRO_{'MPEG4' if n == 'MPEG-4' else n}\t{i}")
    string_function(g2, st, "profile", "stringProfileType", "PROFILES", "profile")

    name_table(st, g1, "components", "COMPONENTS", "components", sorted(vrml_rend.ComponentC),
               lambda n, i: f"#define COM_{'HAnim' if n == 'H-Anim' else n}\t{i}", indent="")
    string_function(g2, st, "component", "stringComponentType", "COMPONENTS", "component")

    # Source order, not sorted.
    name_table(st, g1, "PROTO keywords", "PROTOKEYWORDS", "PROTO keywords",
               vrml_rend.PROTOKeywordC, lambda n, i: f"#define PKW_{n}\t{i}", indent="")
    string_function(g2, st, "PROTO keyword", "stringPROTOKeywordType", "PROTOKEYWORDS",
                    "proto keyword")

    # One-based numbers.
    defines = name_table(st, g1, "MULTITEXTUREMODE keywords", "MULTITEXTUREMODE",
                         "MULTITEXTUREMODE keywords", sorted(vrml_rend.MultiTextureModeC),
                         lambda n, i: f"#define MTMODE_{n}\t{i + 1}")
    string_function(g2, st, "MULTITEXTUREMODE keyword", "stringMULTITEXTUREMODEType",
                    "MULTITEXTUREMODE", "special keyword")
    st.append(defs_string("MULTITEXTUREDefs", defines))

    name_table(st, g1, "MULTITEXTURESOURCE keywords", "MULTITEXTURESOURCE",
               "MULTITEXTURESOURCE keywords", sorted(vrml_rend.MultiTextureSourceC),
               lambda n, i: f"#define MTSRC_{n}\t{i + 1}")

    defines = name_table(st, g1, "TEXTURECOORDINATEGENERATOR keywords",
                         "TEXTURECOORDINATEGENERATOR", "TEXTURECOORDINATEGENERATOR keywords",
                         sorted(vrml_rend.TextureCoordGenModeC),
                         lambda n, i: f"#define TCGT_{n.replace('-', '_')}    {i}")
    st.append(defs_string("TEXTURECOORDINATEGENERATORDefs", defines))
    string_function(g2, st, "MULTITEXTURESOURCE keyword", "stringMULTITEXTURESOURCEType",
                    "MULTITEXTURESOURCE", "special keyword")

    for builtin, array, prefix, names, func, invalid in (
        ("MULTITEXTUREFUNCTION", "MULTITEXTUREFUNCTION", "MTFN", vrml_rend.MultiTextureFunctionC,
         "stringMULTITEXTUREFUNCTIONType", "special keyword"),
        ("X3DSPECIAL", "X3DSPECIAL", "X3DSP", vrml_rend.X3DSpecialC,
         "stringX3DSPECIALType", "special keyword"),
        ("TEXTUREBOUNDARY", "TEXTUREBOUNDARYKEYWORDS", "TB", vrml_rend.TextureBoundaryC,
         "stringTEXTUREBOUNDARYKeywordType", "texture param keyword"),
        ("TEXTUREMAGNIFICATION", "TEXTUREMAGNIFICATIONKEYWORDS", "TMAG",
         vrml_rend.TextureMagnificationC, "stringTEXTUREMAGNIFICATIONKeywordType",
         "texture param keyword"),
        ("TEXTUREMINIFICATION", "TEXTUREMINIFICATIONKEYWORDS", "TMIN",
         vrml_rend.TextureMinificationC, "stringTEXTUREMINIFICATIONKeywordType",
         "texture param keyword"),
        ("TEXTURECOMPRESSION", "TEXTURECOMPRESSIONKEYWORDS", "TC",
         vrml_rend.TextureCompressionC, "stringTEXTURECOMPRESSIONKeywordType",
         "texture param keyword"),
        ("GEOELLIPSOID", "GEOELLIPSOID", "GEOEL", vrml_rend.GEOEllipsoidKeywordC,
         "stringGEOELLIPSOIDType", "keyword"),
        ("GEOSPATIAL", "GEOSPATIAL", "GEOSP", vrml_rend.GEOSpatialKeywordC,
         "stringGEOSPATIALType", "keyword"),
    ):
        name_table(st, g1, f"{builtin} keywords", array, f"{builtin} keywords", sorted(names),
                   lambda n, i, p=prefix: f"#define {p}_{n}\t{i}")
        string_function(g2, st, f"{builtin} keyword", func, array, invalid)

    # Convert to and from EAI field types (EAI types are ASCII).
    text = "char mapFieldTypeToEAItype (int st) {\n\tswitch (st) { \n"
    text += "".join(f"\t\tcase FIELDTYPE_{t}:\treturn EAI_{t};\n" for t in FIELD_TYPES)
    text += "\t\tdefault: return -1;\n\t}\n\treturn -1;\n}\n"
    g2.append(text)
    eai.append(text)
    st.append("char mapFieldTypeToEAItype (int st);\n")

    text = "/* convert an EAI type to an internal type */\nint mapEAItypeToFieldType (char st) {\n\tswitch (st) { \n"
    text += "".join(f"\t\tcase EAI_{t}:\treturn FIELDTYPE_{t};\n" for t in FIELD_TYPES)
    text += "\t\tdefault: return -1;\n\t}\n\treturn -1;\n}\n"
    g2.append(text)
    eai.append(text)
    st.append("int mapEAItypeToFieldType (char st);\n")

    g2.append("/* convert an MF type to an SF type */\nint convertToSFType (int st) {\n\tswitch (st) { \n")
    for t in FIELD_TYPES:
        g2.append(f"\t\tcase FIELDTYPE_{t}:\treturn FIELDTYPE_{t.replace('MF', 'SF', 1)};\n")
    g2.append("\t}\n\treturn -1;\n}\n")
    st.append("int convertToSFType (int st);\n")

    # Field type numbers.
    st.append("\n/* Table of built-in fieldIds */\nextern const char *FIELDTYPES[];\n")
    st.append("extern const int FIELDTYPES_COUNT;\n")
    text = "\n/* Table of Field Types */\n       const char *FIELDTYPES[] = {\n"
    text += "".join(f"\t\"{t}\",\n" for t in FIELD_TYPES)
    text += "};\nconst int FIELDTYPES_COUNT = ARR_SIZE(FIELDTYPES);\n\n"
    g1.append(text)
    eai.append(text)
    st.extend(f"#define FIELDTYPE_{t}\t{number}\n" for number, t in enumerate(FIELD_TYPES))
    st.append("\n")
    st.extend(C_STRUCT[t] + "\n" for t in FIELD_TYPES)
    string_function(g2, st, "fieldtype", "stringFieldtypeType", "FIELDTYPES", "fieldType")

    # Node names.
    st.append("\n/* Table of built-in nodeIds */\nextern const char *NODES[];\n")
    st.append("extern const int NODES_COUNT;\n")
    st.append("\n/* and now the structs for the nodetypes */ \n")
    g1.append("\n/* Table of Node Types */\nconst char *NODES[] = {\n")
    g1.extend(f"\t\"{name}\",\n" for name in node_names)
    g1.append("};\nconst int NODES_COUNT = ARR_SIZE(NODES);\n\n")
    string_function(g2, st, "node", "stringNodeType", "NODES", "node")

    # Default containerField of each node, for the X3D parser.
    st.append("\n/* Table of defaultContainerFields for x3d parsing */\n"
              "extern const short NODE_DEFAULT_CONTAINER[][7];\n")
    g1.append("const short NODE_DEFAULT_CONTAINER[][7] = {\n")
    for name in node_names:
        containers = vrml_rend.DEFAULT_CONTAINER.get(name, ())
        cells = [f"FIELDNAMES_{containers[i]}" if i < len(containers) else "0" for i in range(7)]
        g1.append("{" + ",".join(cells) + "},\n")
    g1.append("};\n")

    # Node structs and virtual tables.
    st.append("\n/* First, a generic struct, contains only the common elements - nicknames for convenience */\n"
              "struct X3D_Node {\n" + COMMON_FIELDS + "};\n" + NODE_MACROS +
              "\n/* now, generated structures for each VRML/X3D Node*/\n")
    g1.append("/* Virtual tables for each node */\n")
    for name in node_names:
        st.append(gen_struct(name, NODES[name]))
        extern, virt = get_rendfunc(name)
        st.append(extern)
        g1.append(virt)
    g1.append("\n")
    g1.append("/* table containing pointers to every virtual struct for each node type */ \n")
    g1.append("struct X3D_Virt* virtTable[] = { \n")
    st.append("extern struct X3D_Virt* virtTable[];\n")
    g1.extend(f"\t &virt_{name},\n" for name in node_names)
    g1.append("\tNULL}; \n\n")

    # createNewX3DNode0 and createNewX3DNode.
    g2.append(CREATE_NODE0_HEAD)
    g2.extend(f"\t\tcase NODE_{n} : {{tmp = MALLOC (struct X3D_{n} *, size = sizeof (struct X3D_{n})); break;}}\n"
              for n in node_names)
    g2.append("\t\tdefault: {printf (\"createNewX3DNode = unknown type %d, this will fail\\n\",nt); return NULL;}\n")
    g2.append(CREATE_NODE0_COMMON)
    for name in node_names:
        g2.append(f"\t\tcase NODE_{name} : {{\n\t\t\tstruct X3D_{name} * tmp2;\n")
        g2.append(f"\t\t\ttmp2 = (struct X3D_{name} *) tmp;\n")
        for field in NODES[name].fields:
            if field.name == "__OccludeNumber":
                init = "tmp2->__OccludeNumber = newOcclude();"
            else:
                init = cinitialize(field.type, "tmp2->" + field.name, field.default)
            g2.append(f"\t\t\t{init};\n")
        g2.append("\t\t\ttmp2->_defaultContainer = 0;\n")
        g2.append("\t\tbreak;\n\t\t}\n")
    g2.append("\t};\n")
    g2.append("\tadd_empty_proto_vectors(tmp);\n")
    g2.append("\treturn tmp;\n}\n")
    g2.append(CREATE_NODE)

    # dump_scene. Only inputOutput fields are dumped. Internal fields and
    # metadata are dumped only when allFields is set: this is the
    # "double_conditional" that the generated comment names.
    g2.append(DUMP_SCENE_HEAD)
    for name in node_names:
        g2.append(f"\t\tcase NODE_{name} : {{\n")
        g2.append(f"\t\t\tstruct X3D_{name} *tmp;\n")
        g2.append(f"\t\t\ttmp = (struct X3D_{name} *) node;\n")
        g2.append("\t\t\tUNUSED(tmp); // compiler warning mitigation\n")
        if name == "PointPickSensor":
            g2.append("\t\t\tspacer fprintf (fp,\" _nparents (int) %d\\n\",vectorSize(tmp->_parentVector)); /* DJTRACK_PICKSENSORS */\n")
            g2.append("\t\t\tfor (i=0; i<vectorSize(tmp->_parentVector); i++) { spacer fprintf (fp,\"    %d: %p\\n\",i, vector_get(struct X3D_Node *, tmp->_parentVector,i)); }\n")
        for field in NODES[name].fields:
            if field.kind != "inputOutput":
                continue
            hidden = field.name.startswith("_") or field.name == "metadata"
            if hidden:
                g2.append("\t\t    if(allFields) {\n")
            g2.append(dump_field(field))
            if hidden:
                g2.append("\t\t    }\n")
        g2.append("\t\t    break;\n\t\t}\n")
    g2.append(DUMP_SCENE_TAIL)

    # OFFSETS_<node>: one row for each field, then a -1 row.
    for name in node_names:
        g1.append(f"\nconst int OFFSETS_{name}[] = {{\n")
        for f in NODES[name].fields:
            g1.append(f"\t(int) FIELDNAMES_{f.name}, (int) offsetof (struct X3D_{name}, {f.name}), "
                      f" (int) FIELDTYPE_{f.type}, (int) KW_{f.kind}, (int) {f.spec}, (int) {f.unca},\n")
        g1.append("\t-1, -1, -1, -1, -1, -1};\n")
    st.append("\nextern const int *NODE_OFFSETS[];\n")
    g1.append("\nconst int *NODE_OFFSETS[] = {\n")
    g1.extend(f"\tOFFSETS_{name},\n" for name in node_names)
    g1.append("\t};\n")

    # NodeFields.h for the classic VRML parser.
    node_fields = []
    for name in node_names:
        node_fields.append(f"\n/* {name} node */\n")
        node_fields.append(f"BEGIN_NODE({name})\n")
        for f in NODES[name].fields:
            if f.name.startswith("_"):
                continue
            macro = NODEFIELDS_KIND[f.kind]
            args = f"{name},{f.name},{f.type.lower()},{f.name},FIELDTYPE_{f.type}"
            if f.kind in ("initializeOnly", "inputOutput"):
                args += f",{f.unca}"
            node_fields.append(f"{macro}({args})\n")
        node_fields.append(f"END_NODE({name})\n")

    # X3D component type of each node.
    st.append("\nint getSAI_X3DNodeType (int FreeWRLNodeType);\n")
    g2.append("\nint getSAI_X3DNodeType (int FreeWRLNodeType) {\n\tswitch (FreeWRLNodeType) {\n")
    g2.extend(f"\tcase NODE_{name}: return {NODES[name].x3d_type}; break;\n" for name in node_names)
    g2.append("\tdefault:return -1;\n\t}\n}\n")

    return {
        SCENEGRAPH_C: file_header("GeneratedCode.c") + license_text + "".join(g1) + "".join(g2),
        LIBEAI_C: file_header("GeneratedCode.c") + license_text + "".join(eai),
        NODEFIELDS_H: file_header("NodeFields.h") + license_text + NODEFIELDS_INTRO + "".join(node_fields),
        STRUCTS_H: (file_header("Structs.h", "  Code here comes almost verbatim from VRMLC.pm\n\n")
                    + license_text + STRUCTS_INTRO + "".join(st) + STRUCTS_END),
    }


def read_license(path=LICENSE_FILE):
    try:
        data = path.read_bytes()
    except OSError as err:
        raise GenerateError(f"cannot read license template {path}: {err.strerror}") from err
    try:
        return data.decode("ascii")
    except UnicodeDecodeError as err:
        raise GenerateError(f"license template {path} is not ASCII") from err


def encode_outputs(texts):
    """Return {path: bytes}. Stop on any non-ASCII character."""
    encoded = {}
    for path in OUTPUTS:
        text = texts[path]
        try:
            encoded[path] = text.encode("ascii")
        except UnicodeEncodeError as err:
            raise GenerateError(f"{path}: output is not ASCII at offset {err.start}") from err
    return encoded


def read_existing(path):
    try:
        return path.read_bytes()
    except FileNotFoundError:
        return None


def check(outputs, root):
    """Compare outputs with the files below root. Return the exit status."""
    status = 0
    for rel, data in outputs.items():
        current = read_existing(root / rel)
        if current is None:
            print(f"MISSING  {rel}", file=sys.stderr)
            status = 1
        elif current != data:
            first = next((i for i, (a, b) in enumerate(zip(current, data, strict=False)) if a != b),
                         min(len(current), len(data)))
            line = current[:first].count(b"\n") + 1
            print(f"DIFFERS  {rel}: first difference at byte {first}, line {line} "
                  f"(file {len(current)} bytes, generated {len(data)} bytes)", file=sys.stderr)
            status = 1
        else:
            print(f"OK       {rel}", file=sys.stderr)
    return status


def write_outputs(outputs, root, make_dirs):
    """Write the changed files. Replace them only after all are ready."""
    changed = []
    for rel, data in outputs.items():
        path = root / rel
        if make_dirs:
            path.parent.mkdir(parents=True, exist_ok=True)
        if not path.parent.is_dir():
            raise GenerateError(f"{path.parent}: directory does not exist")
        current = read_existing(path)
        if current == data:
            print(f"Unchanged: {path}", file=sys.stderr)
            continue
        if current is not None and not os.access(path, os.W_OK):
            raise GenerateError(f"{path}: file is not writable")
        if not os.access(path.parent, os.W_OK):
            raise GenerateError(f"{path.parent}: directory is not writable")
        changed.append((path, data, current is not None))

    temps = []
    try:
        for path, data, exists in changed:
            fd, temp = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
            temps.append(temp)
            with os.fdopen(fd, "wb") as out:
                out.write(data)
                out.flush()
                os.fsync(out.fileno())
            if exists:
                mode = path.stat().st_mode & 0o7777
            else:
                umask = os.umask(0)
                os.umask(umask)
                mode = 0o666 & ~umask
            os.chmod(temp, mode)
        for (path, _data, _exists), temp in zip(changed, temps, strict=True):
            os.replace(temp, path)
            print(f"Generating: {path}", file=sys.stderr)
        temps = []
    finally:
        for temp in temps:
            try:
                os.unlink(temp)
            except FileNotFoundError:
                pass  # os.replace already moved it.


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate the FreeWRL node tables.")
    parser.add_argument("--check", action="store_true",
                        help="compare with the existing files and write nothing")
    parser.add_argument("--out-dir", type=Path,
                        help="write below this directory instead of freex3d/")
    args = parser.parse_args(argv)

    root = args.out_dir.resolve() if args.out_dir else FREEX3D_DIR
    try:
        outputs = encode_outputs(generate(read_license()))
        if args.check:
            return check(outputs, root)
        write_outputs(outputs, root, make_dirs=args.out_dir is not None)
    except (GenerateError, FieldDataError) as err:
        print(f"vrmlc.py: error: {err}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
